# Generated by Django 6.0.6 on 2026-06-26 19:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cursus',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('role', models.CharField(choices=[('STUDENT', 'Étudiant'), ('TEACHER', 'Correcteur / Enseignant'), ('ADMIN', 'Administrateur')], default='STUDENT', max_length=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Livret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrets', to='api.cursus')),
            ],
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('livret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='api.livret')),
            ],
            options={
                'verbose_name': 'Leçon',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QCM', 'Choix multiples'), ('HOLES', 'Texte à trous'), ('OPEN', 'Question ouverte'), ('LINK', 'Éléments à relier'), ('CROSSWORD', 'Verset caché / Grille')], max_length=15)),
                ('statement', models.TextField()),
                ('configuration', models.JSONField(help_text='Stocke les options de QCM, les grilles de lettres ou les solutions.')),
                ('points', models.PositiveIntegerField(default=1)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.lecon')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressionLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LOCKED', 'Verrouillé'), ('IN_PROGRESS', 'En cours'), ('SUBMITTED', 'Soumis pour correction'), ('GRADED', 'Corrigé')], default='LOCKED', max_length=15)),
                ('score', models.PositiveIntegerField(default=0)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('date_graded', models.DateTimeField(blank=True, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='api.lecon')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression Leçon',
                'unique_together': {('user', 'lecon')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(help_text="Stocke la réponse saisie par l'étudiant.")),
                ('is_correct', models.BooleanField(default=False)),
                ('score_assigned', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='api.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réponse Étudiant',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
